---
- name: Install systemd service files
  when:
    - sshd_install_service | bool
    - ansible_facts['service_mgr'] == 'systemd' or
      (ansible_facts['os_family'] == 'RedHat' and ansible_facts['distribution_major_version'] == '7')
  block:
    - name: Install service unit file
      ansible.builtin.template:
        src: "{{ sshd_service_template_service }}"
        dest: "/etc/systemd/system/{{ sshd_service }}.service"
        owner: root
        group: root
        mode: "0644"
      notify:
        - sshd_reload
        - sshd_daemon_reload

    - name: Install instanced service unit file
      ansible.builtin.template:
        src: "{{ sshd_service_template_at_service }}"
        dest: "/etc/systemd/system/{{ sshd_service }}@.service"
        owner: root
        group: root
        mode: "0644"
      notify:
        - sshd_daemon_reload
        - sshd_reload
        - sshd_socket_restart
      when:
        - __sshd_socket_accept | bool

    - name: Install socket unit file
      ansible.builtin.template:
        src: "{{ sshd_service_template_socket }}"
        dest: "/etc/systemd/system/{{ sshd_service }}.socket"
        owner: root
        group: root
        mode: "0644"
      notify:
        - sshd_daemon_reload
        - sshd_reload
        - sshd_socket_restart

# sshd can be run as a service or via socket activation. Those two
# units most not be enabled concurrently. Make sure the unwanted is
# disabled (first) and the wanted one enabled.
- name: Ensure unwanted sshd.(socket|service) unit is disabled
  ansible.builtin.systemd:
    name: "{{ sshd_service }}.{{ _sshd_unit_suffix }}"
    enabled: false
    masked: true
  vars:
    _sshd_unit_suffix: >-
      {{ "socket" if sshd_systemd_unit == 'service'
          else "service" }}
  when:
    - sshd_manage_service | bool
    - ansible_facts['virtualization_type'] | default(None) not in __sshd_skip_virt_env
    - ansible_connection != 'chroot'
  no_log: "{{ ansible_verbosity < 3 }}"

- name: Ensure wanted sshd.(socket|service) unit is enabled
  ansible.builtin.systemd:
    name: "{{ sshd_service }}.{{ sshd_systemd_unit }}"
    enabled: true
    masked: false
  when:
    - sshd_manage_service | bool
    - ansible_facts['virtualization_type'] | default(None) not in __sshd_skip_virt_env
    - ansible_connection != 'chroot'
  no_log: "{{ ansible_verbosity < 3 }}"

# Due to ansible bug 21026, cannot use service module on RHEL 7
- name: Enable service in chroot
  ansible.builtin.command: systemctl enable {{ sshd_service | quote }}  # noqa command-instead-of-module
  when:
    - ansible_connection == 'chroot'
    - sshd_systemd_unit == 'service'
    - ansible_facts['os_family'] == 'RedHat'
    - ansible_facts['distribution_major_version'] | int >= 7
  changed_when: true
