name: Run Ansible Check on Ubuntu

on: [push, pull_request]

jobs:
  ubuntu-latest:
    runs-on: ubuntu-latest
    steps:
      # Important: This sets up your GITHUB_WORKSPACE environment variable
      - name: checkout PR
        uses: actions/checkout@v2

      - name: ansible check with ubuntu:latest
        uses: Jakuje/check-ansible-ubuntu-latest-action@patch-1
        with:
          group: local
          hosts: localhost
          targets: "tests/tests_*.yml"

  ubuntu-20:
    runs-on: ubuntu-latest
    steps:
      # Important: This sets up your GITHUB_WORKSPACE environment variable
      - name: checkout PR
        uses: actions/checkout@v2

      - name: ansible check with ubuntu:20 (focal)
        uses: Jakuje/check-ansible-ubuntu-focal-action@patch-1
        with:
          group: local
          hosts: localhost
          targets: "tests/tests_*.yml"
