name: Ansible CI
on: [push, pull_request]

env:
  ANSIBLE_INJECT_FACT_VARS: "false"

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        scenario:
          - os_image: alpine:latest
            req_file: tests/requirements.yml
          - os_image: quay.io/centos/centos:stream8
            req_file: tests/requirements.yml
          - os_image: quay.io/centos/centos:stream9
            req_file: tests/requirements.yml
          - os_image: quay.io/centos/centos:stream10
            req_file: tests/requirements.yml
          - os_image: debian:bullseye
            req_file: tests/requirements-no-fedora-lsr.yml
          - os_image: debian:bookworm
            req_file: tests/requirements.yml
          - os_image: debian:latest
            req_file: tests/requirements.yml
          - os_image: fedora:latest
            req_file: tests/requirements.yml
          - os_image: ubuntu:22.04
            req_file: tests/requirements-no-fedora-lsr.yml
          - os_image: ubuntu:24.04
            req_file: tests/requirements.yml
          - os_image: ubuntu:latest
            req_file: tests/requirements.yml
          # - os_image: opensuse/tumbleweed:latest # too odd
          #   req_file: tests/requirements.yml
          - os_image: opensuse/leap:latest
            req_file: tests/requirements-no-fedora-lsr.yml

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Test Ansible SSHD Role
        uses: Jakuje/check-ansible-action@main
        with:
          image: ${{ matrix.scenario.os_image }}
          group: local
          hosts: localhost
          targets: "tests/tests_*.yml"
          requirements: ${{ matrix.scenario.req_file }}
