name: Run tests on Fedora latest

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Important: This sets up your GITHUB_WORKSPACE environment variable
      - name: checkout PR
        uses: actions/checkout@v2

      - name: ansible check with fedora:latest
        uses: Jakuje/check-ansible-fedora-latest-action@patch-3
        with:
          group: local
          hosts: localhost
          targets: "tests/tests_*.yml"
